Shopware.Component.register('sw-cms-el-ict-overview-cards-6', () => import('./component'));
Shopware.Component.register('sw-cms-el-config-ict-overview-cards-6', () => import('./config'));
Shopware.Component.register('sw-cms-el-preview-ict-overview-cards-6', () => import('./preview'));

Shopware.Service('cmsService').registerCmsElement({
    name: 'ict-overview-cards-6',
    label: 'ict-cms-bundle-element.cms.elements.ictOverviewCards6.label',
    component: 'sw-cms-el-ict-overview-cards-6',
    configComponent: 'sw-cms-el-config-ict-overview-cards-6',
    previewComponent: 'sw-cms-el-preview-ict-overview-cards-6',
    cardTemplates: {
        iconShape: 'square',
        iconSize: '80',
        iconAlignment: 'left',
        iconBackgroundColor: 'transparent',
        iconColor: '#005AE5',
        iconOutlineColor: 'transparent',
        iconOutlineThickness: '0',
        iconOutlinePosition: 'inside',
        iconBorderRadius: '8',
        iconImage: null,
        iconHoverEffect: 'none',
        headline: 'Card Title',
        headlineSize: '20',
        headlineLineHeight: '26',
        headlineAlignment: 'left',
        headlineColor: '#1a1a2e',
        subheadline: '',
        subheadlineSize: '16',
        subheadlineLineHeight: '22',
        subheadlineAlignment: 'left',
        subheadlineColor: '#52667a',
        showBodyText: true,
        bodyText: 'Card description text goes here.',
        bodyTextAlignment: 'left',
        bodyTextSize: '14',
        bodyTextLineHeight: '22',
        bodyTextColor: '#52667a',
        showDetailRows: false,
        detailRows: [],
        detailRowsTitleAlignment: 'left',
        detailRowsTitleSize: '14',
        detailRowsTitleLineHeight: '22',
        detailRowsTitleFontWeight: '700',
        detailRowsValueAlignment: 'right',
        detailRowsValueSize: '14',
        detailRowsValueLineHeight: '22',
        detailRowsValueFontWeight: '400',
        detailRowsOutlineColor: '#e4e4e3',
        detailRowsOutlineThickness: '1',
        infoText: '',
        infoTextAlignment: 'left',
        infoTextSize: '14',
        infoTextLineHeight: '22',
        infoTextColor: '#1a1a2e',
        infoTextFontWeight: '600',
        buttons: [
            {
                show: true,
                buttonText: 'Learn More',
                buttonLinkType: 'internal',
                buttonUrl: '',
                buttonTarget: '_self',
                buttonTextColor: '#FFFFFF',
                buttonHoverTextColor: '#FFFFFF',
                buttonBorderColor: 'transparent',
                buttonHoverBorderColor: 'transparent',
                buttonBorderStyle: 'solid',
                buttonBorderWidth: 0,
                buttonBorderRadius: 6
            }
        ],
        mediaPosition: 'center',
        mediaWidth: '100',
        contentWidth: '100',
        mediaDisplayMode: 'crop',
        mediaHeight: '200',
        cardMainBackgroundType: 'color',
        cardMainBackgroundColor: '#FFFFFF',
        cardMainBackgroundImage: null,
        cardMainBackgroundVideo: null,
        cardMainBackgroundVideoUploadType: 'file',
        cardMainBackgroundVideoUploadUrl: '',
        cardMainBackgroundGradientColor1: '#005AE5',
        cardMainBackgroundGradientColor2: '#0080FF',
        cardMainBackgroundGradientDirection: 'top',
        cardBackgroundType: 'image',
        cardBackgroundColor: '#FFFFFF',
        cardBackgroundImage: null,
        cardBackgroundVideo: null,
        cardBackgroundVideoUploadType: 'file',
        cardBackgroundVideoUploadUrl: '',
        cardBackgroundGradientColor1: '#005AE5',
        cardBackgroundGradientColor2: '#0080FF',
        cardBackgroundGradientDirection: 'top'
    },
    defaultConfig: {
        backgroundType: { source: 'static', value: 'color' },
        backgroundColor: { source: 'static', value: '#f8f9fa' },
        backgroundImage: { source: 'static', value: null },
        backgroundVideo: { source: 'static', value: null },
        backgroundVideoUploadType: { source: 'static', value: 'file' },
        backgroundVideoUploadUrl: { source: 'static', value: '' },
        backgroundGradientColor1: { source: 'static', value: '#005AE5' },
        backgroundGradientColor2: { source: 'static', value: '#0080FF' },
        backgroundGradientDirection: { source: 'static', value: 'top' },
        numberOfColumns: { source: 'static', value: 3 },
        cardSpacing: { source: 'static', value: 24 },
        verticalAlignment: { source: 'static', value: 'stretch' },
        cards: { source: 'static', value: [] }
    }
});
